/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AgentsAgentIdDashboardRouteImport } from './routes/agents.$agentId_.dashboard'
import { Route as AgentsAgentIdJobsRouteImport } from './routes/agents.$agentId_.jobs'
import { Route as AgentsAgentIdNoteRouteImport } from './routes/agents.$agentId_.note'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdDashboardRoute = AgentsAgentIdDashboardRouteImport.update({
  id: '/agents/$agentId_/dashboard',
  path: '/agents/$agentId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdJobsRoute = AgentsAgentIdJobsRouteImport.update({
  id: '/agents/$agentId_/jobs',
  path: '/agents/$agentId/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdNoteRoute = AgentsAgentIdNoteRouteImport.update({
  id: '/agents/$agentId_/note',
  path: '/agents/$agentId/note',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/agents/$agentId/dashboard': typeof AgentsAgentIdDashboardRoute
  '/agents/$agentId/jobs': typeof AgentsAgentIdJobsRoute
  '/agents/$agentId/note': typeof AgentsAgentIdNoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/agents/$agentId/dashboard': typeof AgentsAgentIdDashboardRoute
  '/agents/$agentId/jobs': typeof AgentsAgentIdJobsRoute
  '/agents/$agentId/note': typeof AgentsAgentIdNoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/agents/$agentId_/dashboard': typeof AgentsAgentIdDashboardRoute
  '/agents/$agentId_/jobs': typeof AgentsAgentIdJobsRoute
  '/agents/$agentId_/note': typeof AgentsAgentIdNoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/new'
    | '/api/files'
    | '/api/health'
    | '/agents/$agentId/dashboard'
    | '/agents/$agentId/jobs'
    | '/agents/$agentId/note'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/new'
    | '/api/files'
    | '/api/health'
    | '/agents/$agentId/dashboard'
    | '/agents/$agentId/jobs'
    | '/agents/$agentId/note'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/agents/$agentId'
    | '/agents/new'
    | '/api/files'
    | '/api/health'
    | '/agents/$agentId_/dashboard'
    | '/agents/$agentId_/jobs'
    | '/agents/$agentId_/note'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AgentsAgentIdDashboardRoute: typeof AgentsAgentIdDashboardRoute
  AgentsAgentIdJobsRoute: typeof AgentsAgentIdJobsRoute
  AgentsAgentIdNoteRoute: typeof AgentsAgentIdNoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId_/dashboard': {
      id: '/agents/$agentId_/dashboard'
      path: '/agents/$agentId/dashboard'
      fullPath: '/agents/$agentId/dashboard'
      preLoaderRoute: typeof AgentsAgentIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId_/jobs': {
      id: '/agents/$agentId_/jobs'
      path: '/agents/$agentId/jobs'
      fullPath: '/agents/$agentId/jobs'
      preLoaderRoute: typeof AgentsAgentIdJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId_/note': {
      id: '/agents/$agentId_/note'
      path: '/agents/$agentId/note'
      fullPath: '/agents/$agentId/note'
      preLoaderRoute: typeof AgentsAgentIdNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiHealthRoute: ApiHealthRoute,
  AgentsAgentIdDashboardRoute: AgentsAgentIdDashboardRoute,
  AgentsAgentIdJobsRoute: AgentsAgentIdJobsRoute,
  AgentsAgentIdNoteRoute: AgentsAgentIdNoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
