import * as stylex from "@stylexjs/stylex";
import { colors } from "../../styles/tokens.stylex";

export const agentStyles = stylex.create({
  page: {
    maxWidth: 560,
    marginInline: "auto",
    paddingBlock: { default: 24, "@media (max-width: 700px)": 8 },
  },
  title: {
    fontSize: 28,
    fontWeight: 500,
    letterSpacing: "-0.7px",
    marginBlock: 12,
  },
  muted: { color: colors.muted },
  form: { display: "flex", flexDirection: "column", gap: 24, marginTop: 36 },
  field: { display: "flex", flexDirection: "column", gap: 8, fontSize: 13 },
  input: {
    width: "100%",
    padding: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.surface,
    color: colors.foreground,
    fontFamily: "inherit",
    fontSize: { default: "inherit", "@media (max-width: 700px)": 16 },
    outlineOffset: 3,
  },
  textarea: { minHeight: 132, resize: "vertical" },
  characters: {
    minWidth: 0,
    flexWrap: "wrap",
    display: "flex",
    gap: 12,
    borderWidth: 0,
    borderStyle: "solid",
    padding: 0,
    margin: 0,
  },
  character: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 6,
    backgroundColor: colors.surface,
    cursor: "pointer",
  },
  actions: { display: "flex", alignItems: "center", gap: 20, marginTop: 8 },
  primary: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: 10,
    paddingInline: 18,
    borderWidth: 0,
    borderStyle: "solid",
    borderRadius: 6,
    backgroundColor: colors.accent,
    color: colors.onAccent,
    fontFamily: "inherit",
    fontSize: { default: "inherit", "@media (max-width: 700px)": 16 },
    textDecoration: "none",
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  link: { color: colors.muted, textDecoration: "none" },
  error: { color: colors.review, paddingBlock: 12 },
  instructions: {
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    marginBlock: 24,
  },
  empty: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    marginTop: 40,
    paddingTop: 24,
  },
});
