import * as stylex from "@stylexjs/stylex";
import { motion } from "./motion.stylex";
import { colors } from "./tokens.stylex";

const arrive = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(6px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const feedStyles = stylex.create({
  page: {
    maxWidth: 780,
    marginInline: "auto",
    paddingTop: { default: 12, "@media (max-width: 700px)": 0 },
    paddingBottom: "env(safe-area-inset-bottom)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 28,
  },
  title: {
    fontSize: { default: 34, "@media (max-width: 700px)": 30 },
    fontWeight: 550,
    letterSpacing: "-1.2px",
    margin: 0,
    lineHeight: 1.15,
  },
  subtitle: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 8,
    marginBottom: 0,
  },
  headerActions: { display: "flex", alignItems: "center", gap: 5 },
  buttonLabel: {
    display: { default: "inline", "@media (max-width: 500px)": "none" },
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    paddingBottom: 12,
  },
  filters: {
    display: "flex",
    gap: 4,
    borderWidth: 0,
    padding: 0,
    margin: 0,
    minWidth: 0,
  },
  filter: { paddingInline: 12, borderRadius: 6, minHeight: 32 },
  selectedFilter: {
    color: colors.foreground,
    backgroundColor: colors.selected,
    fontWeight: 500,
  },
  status: { fontSize: 11, color: colors.muted, margin: 0 },
  statusAction: {
    fontSize: 11,
    color: colors.muted,
    paddingInline: 8,
    minHeight: 32,
  },
  stream: { display: "flex", flexDirection: "column" },
  timeSection: { marginTop: 28 },
  timeHeading: {
    fontSize: 12,
    fontWeight: 550,
    color: colors.muted,
    margin: 0,
    paddingBottom: 6,
  },
  article: {
    paddingBlock: 28,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    animationName: arrive,
    animationDuration: motion.slow,
    animationTimingFunction: motion.easeOut,
  },
  content: { minWidth: 0 },
  openArticle: {
    display: "block",
    width: "100%",
    padding: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    color: colors.foreground,
    cursor: "pointer",
    textAlign: "left",
    outlineOffset: 5,
    borderRadius: 2,
  },
  headline: {
    fontFamily: "inherit",
    fontSize: { default: 21, "@media (max-width: 700px)": 20 },
    fontWeight: 550,
    lineHeight: 1.22,
    letterSpacing: "-0.45px",
    marginTop: 10,
    marginBottom: 9,
    textWrap: "pretty",
    color: {
      default: colors.foreground,
      ":is(button:hover > *)": colors.accent,
    },
    transitionProperty: "color",
    transitionDuration: motion.fast,
  },
  updateHeadline: {
    fontFamily: "inherit",
    fontSize: { default: 18, "@media (max-width: 700px)": 17 },
    fontWeight: 550,
    letterSpacing: "-0.3px",
    lineHeight: 1.35,
  },
  summary: {
    fontSize: 15,
    lineHeight: 1.65,
    margin: 0,
    color: colors.foreground,
    whiteSpace: "pre-line",
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  imageButton: {
    display: "block",
    width: "100%",
    maxWidth: 440,
    marginTop: 18,
    padding: 0,
    borderWidth: 0,
    overflow: "hidden",
    borderRadius: 4,
    cursor: "pointer",
    backgroundColor: colors.surface,
    outlineOffset: 4,
  },
  image: {
    display: "block",
    width: "100%",
    aspectRatio: "16 / 9",
    objectFit: "cover",
    transitionProperty: "transform",
    transitionDuration: motion.slow,
    transform: { default: "scale(1)", ":is(button:hover > *)": "scale(1.025)" },
  },
  meta: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 7,
    fontSize: 11,
    lineHeight: 1.5,
    color: colors.muted,
  },
  source: { color: colors.foreground, fontWeight: 500 },
  dot: {
    width: 4,
    height: 4,
    borderRadius: "50%",
    backgroundColor: colors.faint,
  },
  important: { color: colors.accent, fontWeight: 550 },
  update: { paddingBlock: 22 },
  updateMarker: { display: "flex", alignItems: "center", gap: 6 },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 5,
    marginTop: 14,
  },
  action: { fontSize: 11, paddingInline: 7 },
  activeAction: { color: colors.accent, backgroundColor: colors.selected },
  actionSpacer: { flex: 1 },
  primary: {
    paddingInline: 14,
    paddingBlock: 8,
    backgroundColor: colors.accent,
    color: colors.onAccent,
    fontWeight: 500,
    borderRadius: 6,
  },
  secondary: {
    paddingInline: 12,
    paddingBlock: 8,
    backgroundColor: colors.bubble,
    color: colors.foreground,
  },
  muted: { color: colors.muted },
  loading: { paddingBlock: 80, color: colors.muted, textAlign: "center" },
  loadMore: { marginBlock: 28, display: "flex", justifyContent: "center" },
  empty: {
    paddingBlock: { default: 72, "@media (max-width: 700px)": 48 },
    maxWidth: 560,
  },
  emptyIcon: { color: colors.accent, marginBottom: 22 },
  emptyTitle: {
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: 28,
    lineHeight: 1.2,
    fontWeight: 500,
    letterSpacing: "-0.6px",
    marginTop: 0,
    marginBottom: 12,
  },
  emptyText: {
    color: colors.muted,
    lineHeight: 1.7,
    fontSize: 14,
    maxWidth: 460,
    marginBottom: 24,
  },
  emptySources: {
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
    paddingTop: 24,
    marginTop: 28,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    color: colors.muted,
    fontSize: 11,
  },
  notice: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
    paddingBlock: 12,
    fontSize: 12,
    color: colors.muted,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  error: {
    color: colors.review,
    fontSize: 12,
    margin: 0,
    overflowWrap: "anywhere",
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 20,
    backgroundColor: "#00000055",
    opacity: {
      default: 1,
      ":is([data-starting-style], [data-ending-style])": 0,
    },
    transitionProperty: "opacity",
    transitionDuration: motion.base,
  },
  dialog: {
    position: "fixed",
    zIndex: 21,
    inset: { default: "24px 24px 24px auto", "@media (max-width: 700px)": 0 },
    width: {
      default: "min(700px, calc(100vw - 48px))",
      "@media (max-width: 700px)": "100%",
    },
    maxHeight: "100dvh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderRadius: { default: 10, "@media (max-width: 700px)": 0 },
    backgroundColor: colors.background,
    color: colors.foreground,
    fontFamily:
      "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 13,
    lineHeight: 1.5,
    boxShadow: "0 12px 70px #00000030",
    transform: {
      default: "translateX(0)",
      ":is([data-starting-style], [data-ending-style])": "translateX(24px)",
    },
    opacity: {
      default: 1,
      ":is([data-starting-style], [data-ending-style])": 0,
    },
    transitionProperty: "transform, opacity",
    transitionDuration: motion.slow,
    transitionTimingFunction: motion.easeOut,
  },
  dialogHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
    paddingInline: { default: 28, "@media (max-width: 700px)": 20 },
    paddingTop: "max(16px, env(safe-area-inset-top))",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    gap: 12,
  },
  dialogTitle: {
    fontSize: 16,
    fontWeight: 550,
    letterSpacing: "-0.3px",
    margin: 0,
  },
  dialogScroll: {
    overflowY: "auto",
    overscrollBehavior: "contain",
    minHeight: 0,
    flex: 1,
    paddingInline: { default: 28, "@media (max-width: 700px)": 20 },
    paddingTop: 28,
    paddingBottom: 32,
  },
  readerScroll: {
    paddingInline: { default: 40, "@media (max-width: 700px)": 20 },
  },
  readerHeadline: {
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: { default: 34, "@media (max-width: 700px)": 28 },
    fontWeight: 500,
    lineHeight: 1.18,
    letterSpacing: "-0.8px",
    marginTop: 14,
    marginBottom: 18,
    overflowWrap: "anywhere",
  },
  readerImage: {
    width: "100%",
    maxHeight: 320,
    objectFit: "cover",
    display: "block",
    borderRadius: 4,
    marginBottom: 24,
    aspectRatio: "1.7 / 1",
  },
  readerBody: { fontSize: 15, lineHeight: 1.8, overflowWrap: "anywhere" },
  why: {
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: colors.accent,
    paddingLeft: 14,
    marginTop: 28,
    marginBottom: 24,
    fontSize: 13,
    lineHeight: 1.7,
    color: colors.muted,
  },
  whyLabel: {
    display: "block",
    color: colors.foreground,
    fontSize: 11,
    fontWeight: 550,
    marginBottom: 4,
  },
  citations: {
    marginTop: 30,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingTop: 20,
  },
  citationList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  link: {
    color: colors.accent,
    textDecorationColor: colors.border,
    textUnderlineOffset: 4,
    overflowWrap: "anywhere",
  },
  externalLink: {
    display: "inline-flex",
    gap: 7,
    alignItems: "center",
    color: colors.accent,
    textDecoration: "none",
    fontWeight: 500,
    fontSize: 12,
    paddingBlock: 8,
  },
  dialogFooter: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
    gap: 10,
    paddingInline: { default: 28, "@media (max-width: 700px)": 20 },
    paddingTop: 14,
    paddingBottom: "max(14px, env(safe-area-inset-bottom))",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  form: { display: "flex", flexDirection: "column", minHeight: 0, flex: 1 },
  formSection: {
    borderWidth: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    padding: 0,
    paddingTop: 24,
    margin: 0,
    marginTop: 28,
  },
  firstSection: { borderTopWidth: 0, paddingTop: 0, marginTop: 0 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 550,
    marginTop: 0,
    marginBottom: 12,
  },
  field: { display: "flex", flexDirection: "column", gap: 7, marginTop: 18 },
  label: { fontSize: 12, fontWeight: 500 },
  hint: { fontSize: 12, lineHeight: 1.6, color: colors.muted, margin: 0 },
  input: {
    width: "100%",
    boxSizing: "border-box",
    backgroundColor: colors.surface,
    color: colors.foreground,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    paddingBlock: 10,
    paddingInline: 12,
    fontSize: 13,
    lineHeight: 1.5,
    outlineColor: colors.accent,
    outlineOffset: 2,
    fontFamily: "inherit",
  },
  textarea: { resize: "vertical", minHeight: 90 },
  checkboxRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    cursor: "pointer",
    paddingBlock: 8,
    fontSize: 13,
  },
  checkbox: {
    width: 16,
    height: 16,
    margin: 2,
    flexShrink: 0,
    accentColor: colors.accent,
  },
  checkboxText: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    flex: 1,
    minWidth: 0,
  },
  sources: { display: "flex", flexDirection: "column", gap: 4 },
  sourceRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    paddingBlock: 6,
  },
  sourceName: { fontWeight: 500, overflowWrap: "anywhere" },
  sourceUrl: {
    fontSize: 11,
    color: colors.muted,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: {
      default: 470,
      "@media (max-width: 700px)": "calc(100vw - 140px)",
    },
  },
  sourceChoice: {
    display: "flex",
    flex: 1,
    minWidth: 0,
    gap: 10,
    alignItems: "center",
    paddingBlock: 6,
    cursor: "pointer",
  },
  presets: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 12 },
  addSource: {
    display: "grid",
    gridTemplateColumns: {
      default: "1fr 1.5fr auto",
      "@media (max-width: 500px)": "1fr",
    },
    gap: 8,
    alignItems: "end",
    marginTop: 12,
  },
  smallField: { display: "flex", flexDirection: "column", gap: 5, minWidth: 0 },
  feedback: { fontSize: 12, color: colors.accent, margin: 0 },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
