import * as stylex from "@stylexjs/stylex";
import { motion } from "./motion.stylex";
import { colors } from "./tokens.stylex";

export const jobsStyles = stylex.create({
  desktopOnly: {
    display: { default: null, "@media(max-width:700px)": "none" },
  },
  mobileOnly: {
    display: { default: "none", "@media(max-width:700px)": "initial" },
  },
  mobileControl: {
    display: { default: "none", "@media(max-width:700px)": "inline-flex" },
  },
  workerResponse: {
    whiteSpace: "normal",
    fontSize: 15,
    lineHeight: 1.75,
    marginTop: 4,
  },
  workerAuthor: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: 500,
    marginTop: 14,
  },
  workerExchange: { marginBlock: 24, minWidth: 0 },
  workerPrompt: { fontWeight: 500, color: colors.foreground },
  messageTime: { color: colors.muted, fontSize: 11 },
  deliveryState: {
    color: colors.muted,
    fontSize: 12,
    marginBlock: 6,
    lineHeight: 1.6,
  },
  secondaryNavigation: { color: colors.muted, fontSize: 12 },
  secondarySummary: {
    cursor: "pointer",
    minHeight: 44,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    outlineOffset: 3,
    "::after": { content: '"⌄"' },
  },
  secondaryActions: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
  },
  backToWorker: { alignSelf: "flex-start", marginBottom: 8 },
  previewReceipt: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 1.6,
    overflowWrap: "anywhere",
    marginBlock: 8,
  },
  receiptSummary: {
    cursor: "pointer",
    paddingBlock: 8,
    minHeight: 44,
    boxSizing: "border-box",
    outlineOffset: 3,
  },
  workerDiscussion: { display: "flex", flexDirection: "column", minWidth: 0 },
  workerLog: {
    overflowY: "visible",
    overflowWrap: "anywhere",
    minWidth: 0,
    order: 2,
  },
  workerComposer: {
    order: 0,
    scrollMarginBlock: 12,
    borderRadius: 10,
    padding: 8,
    boxShadow: null,
  },
  workerTextarea: {
    height: {
      default: 72,
      "@media(max-width:700px)":
        "clamp(56px, calc(var(--roost-viewport-height, 100dvh) * .10), 80px)",
    },
    minHeight: { default: 72, "@media(max-width:700px)": 56 },
    resize: { default: "vertical", "@media(max-width:700px)": "none" },
    boxSizing: "border-box",
  },
  composerActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 0,
  },
  composerButton: {
    minWidth: 0,
    whiteSpace: "normal",
    maxWidth: "100%",
    paddingInline: 8,
  },
  sendButton: {
    minWidth: 0,
    whiteSpace: "normal",
    maxWidth: "100%",
    backgroundColor: {
      default: colors.accent,
      ":enabled:hover": colors.accent,
    },
    color: { default: colors.onAccent, ":enabled:hover": colors.onAccent },
    opacity: { default: 1, ":disabled": 0.4 },
    fontSize: { default: 12, "@media(max-width:700px)": 14 },
    fontWeight: 500,
    paddingInline: 10,
  },
  composerHelp: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 1.5,
    marginBlock: 6,
  },
  composerNotice: {
    order: 1,
    marginBlock: 6,
    ":empty": { display: "none" },
  },
  history: { minWidth: 0 },
  historySummary: {
    display: "list-item",
    color: colors.muted,
    cursor: "pointer",
    minHeight: 44,
    paddingBlock: 12,
    fontSize: 13,
    boxSizing: "border-box",
    outlineOffset: 3,
  },
  workspaceDetails: {
    minWidth: 0,
    order: 1,
  },
  workspaceDetailsSummary: {
    display: "list-item",
    cursor: "pointer",
    minHeight: 44,
    paddingBlock: 14,
    fontSize: 13,
    fontWeight: 500,
    outlineOffset: 3,
  },
  discussionColumn: {
    minWidth: 0,
    order: 0,
  },
  wrappingButton: {
    whiteSpace: "normal",
    textAlign: "left",
    maxWidth: "100%",
    overflowWrap: "anywhere",
  },
  conversationPanel: { height: 580, minWidth: 0, maxHeight: "75svh" },
  page: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: {
      default: "calc(100svh - 40px)",
      "@media(max-width:700px)": "100%",
    },
    minHeight: 0,
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: { default: 28, "@media(max-width:700px)": 12 },
    paddingBottom: {
      default: 28,
      "@media(max-width:700px)":
        "max(12px, var(--roost-bottom-inset, env(safe-area-inset-bottom)))",
    },
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  filters: {
    display: "flex",
    gap: { default: 8, "@media(max-width:700px)": 4 },
    flexWrap: "wrap",
  },
  selected: { backgroundColor: colors.selected, color: colors.foreground },
  title: {
    fontSize: 18,
    fontWeight: 500,
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: "anywhere",
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 500,
    marginTop: 0,
    marginBottom: 12,
  },
  muted: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 1.7,
    overflowWrap: "anywhere",
  },
  list: { listStyle: "none", padding: 0, margin: 0 },
  row: {
    display: "flex",
    justifyContent: "space-between",
    gap: { default: 20, "@media(max-width:700px)": 12 },
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingBlock: 16,
  },
  rowMain: { minWidth: 0 },
  jobLink: {
    fontSize: 14,
    fontWeight: 500,
    color: colors.foreground,
    textDecoration: "none",
    overflowWrap: "anywhere",
    display: "inline-flex",
    alignItems: "center",
    minHeight: { default: 24, "@media(max-width:700px)": 44 },
    outlineOffset: 3,
    ":hover": { textDecoration: "underline" },
  },
  summary: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 1.7,
    marginBlock: 6,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  status: { fontSize: 12, color: colors.muted },
  feedback: { color: colors.accent },
  blocked: { color: colors.review },
  rowMeta: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  rowActions: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
    flexShrink: 0,
    maxWidth: { default: "none", "@media(max-width:700px)": 120 },
  },
  actionLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    color: colors.foreground,
    fontWeight: 500,
    textDecoration: "none",
    minHeight: { default: 28, "@media(max-width:700px)": 44 },
    paddingInline: 6,
    borderRadius: 5,
    outlineOffset: 3,
    ":hover": { backgroundColor: colors.bubble },
  },
  link: {
    color: colors.foreground,
    fontSize: 12,
    textUnderlineOffset: 3,
    overflowWrap: "anywhere",
  },
  back: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: 12,
    color: colors.muted,
    minHeight: { default: 28, "@media(max-width:700px)": 44 },
    marginBottom: { default: 20, "@media(max-width:700px)": 4 },
    textDecoration: "none",
    outlineOffset: 3,
  },
  heading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    gap: { default: 20, "@media(max-width:700px)": 8 },
    flexWrap: "wrap",
    marginBottom: { default: 28, "@media(max-width:700px)": 12 },
  },
  actions: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  workspace: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: 800,
    gap: 8,
  },
  section: { marginBottom: 28 },
  sectionHeading: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  preview: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.surface,
  },
  previewText: { minWidth: 0, flex: 1 },
  revision: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
    fontSize: 12,
    color: colors.muted,
  },
  discussion: { display: "flex", flexDirection: "column", minWidth: 0 },
  message: {
    marginBlock: 12,
    padding: 12,
    backgroundColor: colors.bubble,
    borderRadius: 12,
  },
  messageText: {
    fontSize: { default: 13, "@media(max-width:700px)": 15 },
    lineHeight: 1.7,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    marginBlock: 8,
  },
  author: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    flexWrap: "wrap",
  },
  composer: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.border, ":focus-within": colors.accent },
    borderRadius: 14,
    padding: 10,
    boxShadow: {
      default: "0 2px 8px #00000003",
      ":focus-within": `0 0 0 3px color-mix(in srgb, ${colors.accent} 14%, transparent)`,
    },
    transitionProperty: "border-color,box-shadow",
    transitionDuration: motion.base,
    transitionTimingFunction: motion.easeOut,
  },
  label: { fontSize: 12, fontWeight: 500, display: "block", padding: 3 },
  textarea: {
    display: "block",
    width: "100%",
    minHeight: 100,
    resize: "vertical",
    backgroundColor: "transparent",
    color: colors.foreground,
    borderWidth: 0,
    outline: "none",
    padding: "8px 3px",
    fontSize: { default: 12, "@media(max-width:700px)": 16 },
    lineHeight: 1.5,
    "::placeholder": { color: colors.muted },
  },
  technical: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    fontSize: 12,
    color: colors.muted,
  },
  technicalSummary: {
    cursor: "pointer",
    paddingBlock: 12,
    minHeight: 44,
    outlineOffset: 3,
  },
  metadata: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0,1fr)",
    gap: "8px 16px",
    fontSize: 12,
  },
  value: { margin: 0, color: colors.foreground, overflowWrap: "anywhere" },
  output: {
    maxHeight: { default: 320, "@media(max-width:700px)": "none" },
    overflowY: { default: "auto", "@media(max-width:700px)": "visible" },
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    fontFamily: "monospace",
    fontSize: 12,
    lineHeight: 1.6,
  },
  error: {
    color: colors.review,
    fontSize: 13,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  empty: { maxWidth: 420, marginInline: "auto", paddingBlock: 64 },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
    fontSize: 12,
  },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    margin: -1,
    padding: 0,
    overflow: "hidden",
    clip: "rect(0,0,0,0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
